version: "3.8"
services:
  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=t1a2y3l4o5r6e7    # Set a password for root
      - MYSQL_DATABASE=devops                # The database name to create
    volumes:
      - db-data:/var/lib/mysql               # Persist MySQL data
    ports:
      - "3307:3306"                          # Map MySQL port to the host

  devops-app:
    image: nawresssjebali/projet_devops
    depends_on:
      - mysql-db
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url": "jdbc:mysql://mysql-db:3306/devops?allowPublicKeyRetrieval=true&useSSL=false",
             "spring.datasource.username": "root",  # Use root user
             "spring.datasource.password": "t1a2y3l4o5r6e7",  # Set the same password as MYSQL_ROOT_PASSWORD
             "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect",
             "spring.jpa.hibernate.ddl-auto": "update"
          }'
    ports:
      - "8082:8082"

volumes:
  db-data:  # This volume is used for persistent MySQL data
